AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RepositoryName:
    Type: String
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      LifecyclePolicy:
        rules:
          - rulePriority: 1
            description: "Keep only one untagged image, expire all others"
            selection:
              tagStatus: untagged
              countType: imageCountMoreThan
              countNumber: 1
            action:
              type: expire