# https://github.com/kciter/aws-ecr-action

name: Create ECR repo

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      ecr-repository:
        description: 'AWS ECR Repository Name'
        required: true
        default: 'crypto-prices-etl'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image and push to ECR
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          region: ${{ github.event.inputs.region}}
          repo: ${{ github.event.inputs.ecr-repository}}
          create_repo: true
